#pragma once

#include "structure/jgl2_glyph.h"
#include "structure/jgl2_string.h"
#include "structure/jgl2_exception.h"
#include "structure/jgl2_color.h"
#include "structure/jgl2_data_contener.h"
#include "structure/jgl2_array.h"
#include "structure/jgl2_locked_queue.h"
#include "structure/jgl2_matrix.h"
#include "structure/jgl2_perlin.h"
#include "structure/jgl2_pool.h"
#include "structure/jgl2_shared_object.h"
#include "structure/jgl2_vector.h"
#include "structure/jgl2_image.h"
#include "structure/jgl2_mouse.h"
#include "structure/jgl2_keyboard.h"
#include "structure/jgl2_font.h"